### ISSUE TITLE
Hello, Chinese Messy code

### ISSUE THREAD

**Issue by 1050298332** [sheip9/Bigdoors_zhcn_translaton#1]
Hello, Chinese Messy code
img
![image](https://user-images.githubusercontent.com/70181406/160413096-78b54436-6cee-4d5c-96d8-9c64507070f0.png)

**Comment by sheip9** [comment]
你转下编码就行了，我这是utf8的

**Comment by sheip9** [comment]
明明都国人没必要用英语问我啊😂

**Comment by 1050298332** [comment]
好的呢 谢了兄弟
